name: MelihStockScannerBot

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu al
        uses: actions/checkout@v6

      - name: Python sürümünü kontrol et
        run: python --version

      - name: Botu çalıştır
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python bot.py
